### ISSUE TITLE
Discuss which text writing language / template the report utilizes

### ISSUE THREAD

**Issue by mac641** [teamulster2/report#8]
* Markdown?
* LaTeX?

**Comment by mac641** [comment]
## Yaml header for Markdown file

```yaml
---
title: title
author: authors
date: \today{}
lang: en-GB
documentclass: scrartcl
mainfont: Arial
sansfont: Arial
monofont: Arial
mathfont: Arial
fontsize: 11pt
header-includes: \usepackage{setspace}
geometry: margin=2cm
papersize: a4
indent: false
linestretch: 1.5
links-as-notes: true
urlcolor: NavyBlue
toc: true
toc-depth: 3
---
```

## Tex file to disable image floating

```tex
\usepackage{float}
\let\origfigure\figure
\let\endorigfigure\endfigure
\renewenvironment{figure}[1][2] {
    \expandafter\origfigure\expandafter[H]
} {
    \endorigfigure
}
```

## Shell command to build pdf using `pandoc`

```shell
pandoc analysis.md -o analysis.pdf --standalone -f markdown -H disable_float.tex --pdf-engine=xelatex
```
